ATTRIBUTE_NAME_ERROR = "__mcd_error__"
ATTRIBUTE_NAME_ERROR_TYPE = "__mcd_error_type__"
ATTRIBUTE_NAME_EXCEPTION = "__mcd_exception__"
ATTRIBUTE_NAME_STACK_TRACE = "__mcd_stack_trace__"

ATTRIBUTE_NAME_REFERENCE = "__reference__"
ATTRIBUTE_NAME_TYPE = "__type__"
ATTRIBUTE_NAME_DATA = "__data__"

ATTRIBUTE_VALUE_TYPE_CALL = "call"
ATTRIBUTE_VALUE_TYPE_BYTES = "bytes"
ATTRIBUTE_NAME_TRACE_ID = "__mcd_trace_id__"
ATTRIBUTE_NAME_RESULT = "__mcd_result__"

CONTEXT_VAR_CLIENT = "_client"
CONTEXT_VAR_UTILS = "__utils"

TRACE_ID_HEADER = "x-mcd-trace-id"

AUTH_TYPE_GCP_SERVICE_ACCOUNT = "GCP_JSON_SERVICE_ACCOUNT_KEY"
AUTH_TYPE_GCP_DEFAULT_CREDENTIALS = "GCP_DEFAULT_CREDENTIALS"
AUTH_TYPE_AWS_ASSUMABLE_ROLE = "AWS_ASSUMABLE_ROLE"

PLATFORM_GENERIC = "Generic"
PLATFORM_GCP = "GCP"
PLATFORM_AWS = "AWS"

STORAGE_TYPE_ENV_VAR = "MCD_STORAGE"
STORAGE_TYPE_S3 = "S3"
STORAGE_TYPE_GCS = "GCS"
