ATTRIBUTE_NAME_ERROR = "__error__"
ATTRIBUTE_NAME_ERROR_TYPE = "__error_type__"
ATTRIBUTE_NAME_EXCEPTION = "__exception__"
ATTRIBUTE_NAME_STACK_TRACE = "__stack_trace__"
ATTRIBUTE_NAME_REFERENCE = "__reference__"
ATTRIBUTE_NAME_TYPE = "__type__"

ATTRIBUTE_VALUE_TYPE_CALL = "call"

CONTEXT_VAR_CLIENT = "_client"
CONTEXT_VAR_UTILS = "__utils"
