ATTRIBUTE_NAME_ERROR = "__mcd_error__"
ATTRIBUTE_NAME_ERROR_TYPE = "__mcd_error_type__"
ATTRIBUTE_NAME_EXCEPTION = "__mcd_exception__"
ATTRIBUTE_NAME_STACK_TRACE = "__mcd_stack_trace__"

ATTRIBUTE_NAME_REFERENCE = "__reference__"
ATTRIBUTE_NAME_TYPE = "__type__"
ATTRIBUTE_NAME_DATA = "__data__"

ATTRIBUTE_VALUE_TYPE_CALL = "call"
ATTRIBUTE_VALUE_TYPE_BYTES = "bytes"

CONTEXT_VAR_CLIENT = "_client"
CONTEXT_VAR_UTILS = "__utils"
