version: 2.1

orbs:
  docker: circleci/docker@2.2.0

commands:
  cmd-trufflehog-scan:
    parameters:
      disable_entropy:
        default: true
        description: Should we disable truffleHog's entropy detection?
        type: boolean
      max_history:
        default: "1"
        description: How far back to scan in git revisions
        type: string
      regexp_rules:
        default: ""
        description: Override default regexp rules with this file.
        type: string
      allowlist_file:
        default: ".circleci/trufflehog_config/allowlist.json"
        description: Add items to this file to allow you to override specific findings.
        type: string
      repo_path:
        default: .
        description: Scan alternate local or remote repo
        type: string
    steps:
    - run:
        command: >
          trufflehog --regex --json \
                     --branch ${CIRCLE_BRANCH} \
                     <<# parameters.allowlist_file >> --allow << parameters.allowlist_file >> <</ parameters.allowlist_file >> \
                     <<# parameters.max_history >> --max_depth=<< parameters.max_history >> <</ parameters.max_history>> \
                     <<# parameters.disable_entropy >> --entropy=False <</ parameters.disable_entropy >> \
                     <<# parameters.regexp_rules >> --rules=<< parameters.regexp_rules >> <</ parameters.regexp_rules >> \
                     << parameters.repo_path >> \
                     | jq '{"reason":.reason,"path": .path}'
        name: Scan using truffleHog

jobs:
  run-trufflehog-scan:
    docker:
    - image: cimg/python:3.10
    steps:
    - checkout
    - run:
        command: pip install truffleHog
        name: Install truffleHog
    - cmd-trufflehog-scan

  run-test-docker:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - docker/build:
          image: mcd/apollo-agent-tests
          extra_build_args: --target tests
          step-name: Run tests in docker build

  build-and-push:
    machine:
      image: ubuntu-2004:202201-02
    parameters:
      docker_hub_repository:
        type: string
      code_version:
        type: string
    steps:
      - checkout
      - docker/check:
          use-docker-credentials-store: true
      - docker/build:
          step-name: Build generic image
          use-buildkit: true  # to build only the required stages
          extra_build_args: --target generic --build-arg code_version=<< parameters.code_version >> --build-arg build_number=<< pipeline.number >>
          image: montecarlodata/<< parameters.docker_hub_repository >>
          tag: latest-generic,<< parameters.code_version >>-generic
      - docker/build:
          step-name: Build cloudrun image
          use-buildkit: true # to build only the required stages
          extra_build_args: --target cloudrun --build-arg code_version=<< parameters.code_version >> --build-arg build_number=<< pipeline.number >>
          image: montecarlodata/<< parameters.docker_hub_repository >>
          tag: latest-cloudrun,<< parameters.code_version >>-cloudrun
      - docker/push:
          image: montecarlodata/<< parameters.docker_hub_repository >>
          tag: latest-generic,<< parameters.code_version >>-generic,latest-cloudrun,<< parameters.code_version >>-cloudrun

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - run-trufflehog-scan:
          # run for all tags and branches, we need to add this so the job is available for build-and-push-prod
          filters: &filters-all-branches-and-tags
            tags:
              only: /.*/
      - run-test-docker:
          requires:
            - run-trufflehog-scan
          filters:
            <<: *filters-all-branches-and-tags
      - build-and-push:
          name: build-and-push-dev
          docker_hub_repository: apollo-pre-release-agent
          code_version: dev-<< pipeline.number >>
          context:
            - docker
          requires:
            - run-test-docker
          filters:
            branches:
              only:
                - dev
      - build-and-push:
          name: build-and-push-prod
          docker_hub_repository: apollo-agent
          code_version: ${CIRCLE_TAG}
          context:
            - docker
          requires:
            - run-test-docker
          filters: # run only for tags starting with v, don't run for branches
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
