version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0.0
  aws-ecr: circleci/aws-ecr@8.1.3
  docker: circleci/docker@2.2.0

commands:
  cmd-trufflehog-scan:
    parameters:
      disable_entropy:
        default: true
        description: Should we disable truffleHog's entropy detection?
        type: boolean
      max_history:
        default: "1"
        description: How far back to scan in git revisions
        type: string
      regexp_rules:
        default: ""
        description: Override default regexp rules with this file.
        type: string
      allowlist_file:
        default: ".circleci/trufflehog_config/allowlist.json"
        description: Add items to this file to allow you to override specific findings.
        type: string
      repo_path:
        default: .
        description: Scan alternate local or remote repo
        type: string
    steps:
    - run:
        command: >
          trufflehog --regex --json \
                     --branch ${CIRCLE_BRANCH} \
                     <<# parameters.allowlist_file >> --allow << parameters.allowlist_file >> <</ parameters.allowlist_file >> \
                     <<# parameters.max_history >> --max_depth=<< parameters.max_history >> <</ parameters.max_history>> \
                     <<# parameters.disable_entropy >> --entropy=False <</ parameters.disable_entropy >> \
                     <<# parameters.regexp_rules >> --rules=<< parameters.regexp_rules >> <</ parameters.regexp_rules >> \
                     << parameters.repo_path >> \
                     | jq '{"reason":.reason,"path": .path}'
        name: Scan using truffleHog
  verify-version-in-docker-image:
    parameters:
      image:
        description: Image name to validate
        type: string
      version:
        description: Expected contents for /app/apollo/agent/version file
        type: string
    steps:
    - run:
        name: Verify version in Docker image
        command: |
          image_version=$(docker run --rm --entrypoint python << parameters.image >> apollo/agent/settings.py)
          if [ $image_version = "<< parameters.version >>" ]
            then exit 0
            else echo "Failed to find expected version, found: $image_version"; exit 1
          fi

jobs:
  run-trufflehog-scan:
    docker:
    - image: cimg/python:3.10
    steps:
    - checkout
    - run:
        command: pip install truffleHog
        name: Install truffleHog
    - cmd-trufflehog-scan

  run-linter:
    docker:
      - image: cimg/python:3.8-node

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv .venv
            . .venv/bin/activate
            pip install --no-cache-dir --upgrade pip
            pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt -r requirements-cloudrun.txt -r requirements-lambda.txt
      - run:
          name: 'Run black / pyright'
          command: |
            . .venv/bin/activate
            black --check .
            pyright

  run-test-docker:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - docker/build:
          image: mcd/apollo-agent-tests
          extra_build_args: --target tests
          step-name: Run tests in docker build

  build-and-push:
    machine:
      image: ubuntu-2004:202201-02
    parameters:
      docker_hub_repository:
        type: string
      code_version:
        type: string
    steps:
      - checkout
      - docker/check:
          use-docker-credentials-store: true
      - docker/build:
          step-name: Build generic image
          use-buildkit: true  # to build only the required stages
          extra_build_args: --target generic --build-arg code_version=<< parameters.code_version >> --build-arg build_number=<< pipeline.number >>
          image: montecarlodata/<< parameters.docker_hub_repository >>
          tag: latest-generic,<< parameters.code_version >>-generic
      - docker/build:
          step-name: Build cloudrun image
          use-buildkit: true # to build only the required stages
          extra_build_args: --target cloudrun --build-arg code_version=<< parameters.code_version >> --build-arg build_number=<< pipeline.number >>
          image: montecarlodata/<< parameters.docker_hub_repository >>
          tag: latest-cloudrun,<< parameters.code_version >>-cloudrun
      - verify-version-in-docker-image:
          image: montecarlodata/<< parameters.docker_hub_repository >>:latest-generic
          version: << parameters.code_version >>,<< pipeline.number >>
      - verify-version-in-docker-image:
          image: montecarlodata/<< parameters.docker_hub_repository >>:latest-cloudrun
          version: << parameters.code_version >>,<< pipeline.number >>
      - docker/push:
          image: montecarlodata/<< parameters.docker_hub_repository >>
          tag: latest-generic,<< parameters.code_version >>-generic,latest-cloudrun,<< parameters.code_version >>-cloudrun

  build-and-push-lambda:
    machine:
      image: ubuntu-2004:202201-02
    parameters:
      aws_ecr_repository:
        type: string
      code_version:
        type: string
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          checkout: false
          repo: << parameters.aws_ecr_repository >>
          tag: << parameters.code_version >>
          extra-build-args: --target lambda --build-arg code_version=<< parameters.code_version >> --build-arg build_number=<< pipeline.number >>
      - verify-version-in-docker-image:
          image: ${AWS_ECR_ACCOUNT_URL}/<< parameters.aws_ecr_repository >>:<< parameters.code_version >>
          version: << parameters.code_version >>,<< pipeline.number >>
      - aws-ecr/tag-image:
          repo: << parameters.aws_ecr_repository >>
          source-tag: << parameters.code_version >>

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - run-trufflehog-scan
      - run-linter
      - run-test-docker:
          # run for all tags and branches, we need to add this so the job is available for build-and-push-prod
          filters:
            tags:
              only: /.*/
      - build-and-push:
          name: build-and-push-dev
          docker_hub_repository: pre-release-agent
          code_version: ${NEXT_VERSION}
          pre-steps:
            - checkout
            - run:
                command: |
                  PIPELINE_NUMBER=<< pipeline.number >>
                  if git describe --tags --abbrev=0; then TAG=$(git describe --tags --abbrev=0); else exit 1; fi
                  VERSION=${TAG#v}
                  echo "NEXT_VERSION=$(echo "$VERSION" | awk 'BEGIN{FS=OFS="."} {$3+=1} 1')rc${PIPELINE_NUMBER}" >> $BASH_ENV
                  source $BASH_ENV
          context:
            - docker
          requires:
            - run-linter
            - run-trufflehog-scan
            - run-test-docker
          filters:
            branches:
              only:
                - dev
#      - build-and-push-lambda:
#          name: build-and-push-lambda-dev
#          aws_ecr_repository: mcd-pre-release-agent
#          code_version: ${NEXT_VERSION}
#          pre-steps:
#            - checkout
#            - run:
#                command: |
#                  PIPELINE_NUMBER=<< pipeline.number >>
#                  if git describe --tags --abbrev=0; then TAG=$(git describe --tags --abbrev=0); else exit 1; fi
#                  VERSION=${TAG#v}
#                  echo "NEXT_VERSION=$(echo "$VERSION" | awk 'BEGIN{FS=OFS="."} {$3+=1} 1')rc${PIPELINE_NUMBER}" >> $BASH_ENV
#                  source $BASH_ENV
#          context:
#            - aws-dev
#          requires:
#            - run-linter
#            - run-trufflehog-scan
#            - run-test-docker
#          filters:
#            branches:
#              only:
#                - dev
      - build-and-push:
          name: build-and-push-prod
          docker_hub_repository: agent
          code_version: ${VERSION_TAG}
          pre-steps:
            - checkout
            - run:
                command: |
                  if git describe --tags --abbrev=0; then TAG=$(git describe --tags --abbrev=0); else exit 1; fi
                  echo "VERSION_TAG=${TAG#v}" >> $BASH_ENV
                  source $BASH_ENV
          context:
            - docker
          requires:
            - run-linter
            - run-trufflehog-scan
            - run-test-docker
          filters: # run only for tags starting with v, don't run for branches
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-and-push-lambda:
          name: build-and-push-lambda-prod
          aws_ecr_repository: mcd-agent
          code_version: ${VERSION_TAG}
          pre-steps:
            - checkout
            - run:
                command: |
                  if git describe --tags --abbrev=0; then TAG=$(git describe --tags --abbrev=0); else exit 1; fi
                  echo "VERSION_TAG=${TAG#v}" >> $BASH_ENV
                  source $BASH_ENV
          context:
            - aws-prod
          requires:
            - run-linter
            - run-trufflehog-scan
            - run-test-docker
          filters: # run only for tags starting with v, don't run for branches
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
